function eiga
eiga = [...
    "アニメ",...
    "ドラマ",...
    "恋愛",...
    "ホラー",...
    "ミュージカル",...
    "スポーツ",...
    "SF",...
    "邦画",...
    "青春",...
    "コメディ",...
    "アクション",...
    "アドベンチャー・冒険",...
    "サイコ",...
    "ドキュメンタリー",...
    "サスペンス",...
    "戦争",...
    "スリラー",...
    "ファンタジー",...
    "ミステリー",...
    "バイオレンス",...
    "伝記"];

reverseStr = '';

%ループの中
n = 85;
l = length(eiga);
time = 0.01;
for i = 1:n
    ind = randi(l, 1);
    msg = sprintf(eiga(ind));
    str = strcat(reverseStr, msg);
    fprintf(str);
    reverseStr = repmat(sprintf('\b'), 1, length(char(msg)));
    time = 0.009545 * exp(0.04652 * i);
    pause(time)
end

%ループ後
fprintf('\n')

for i = 1:10
    disp(msg)
end


end