clear
close all force

global edt_m edt_s bt_stop time

h = 300;
w = 400;
fontsize = 14;

H0 = uifigure;
H0.Position(3) = w;
H0.Position(4) = h;

edt_m = uieditfield(H0,...
    'Value', '3',...
    'Position', [50 h-200 100 30],...
    'HorizontalAlignment', 'right',...
    'FontSize', fontsize);
edt_s = uieditfield(H0,...
    'Value', '00',...
    'Position', [200 h-200 100 30],...
    'HorizontalAlignment', 'right',...
    'FontSize', fontsize);
txt_m = uilabel(H0,...
    'Position', [155 h-198 31 22],...
    'Text', 'm',...
    'FontSize', fontsize);
txt_s = uilabel(H0,...
    'Position', [305 h-198 31 22],...
    'Text', 's',...
    'FontSize', fontsize);

time = uilabel(H0,...
    'Position', [115 170 150 100],...
    'Text', '3:00',...
    'FontSize', 50);

bt_start = uibutton(H0,...
    'Text', 'Start',...
    'Position', [70 50 70 30],...
    'FontSize', 18,...
    'ButtonPushedFcn', @(bt_start, event) timer_start);

bt_stop = uibutton(H0, 'state',...
    'Text', 'Stop',...
    'Position', [160 50 70 30],...
    'FontSize', 18);

function timer_start
global edt_m edt_s time bt_stop
tic
tmp = time.Text;
ml = str2double(edt_m.Value);
sl = str2double(edt_s.Value);
flag = 0;
while bt_stop.Value == 0 && flag == 0
    t = round(toc);
    m = fix((t+(60-sl))/60);
    s = rem(t+(60-sl), 60); 
    str = sprintf('%d:%02d', (ml-m), (59-s));
    time.Text = str;
    if (ml-m) <= 0 && (59-s) <= 0
        flag = 1;
    end
    pause(0.1)
    drawnow
end
if flag == 1
    hallelujah(3)
end
bt_stop.Value = 0;
time.Text = sprintf('%d:%02d', str2double(edt_m.Value), str2double(edt_s.Value));
end