function meshi(varargin)
% MESHI : 飯食いに行く店を決定するルーレット
%
% Usage : MESHI(period)
%   [Input]
%   period : time period (ex. 'l' or 'd') [Default] 'd'
% 
% contents :
%   グランブッフェ - イオンの食べ放題

% % - Release Notes -
% #[1.0] -2020/12/15-  by K.Kamura
% #[2.0] -2021/5/8-  by K.Kamura
%   - Automatic switch time period -

if nargin == 0
    date = datetime('now');
    h = hour(date);
    if h < 15
        period = 'l';
    else
        period = 'd';
    end
elseif nargin == 1
    period = varargin{1};
else
    error('error')
end

common = ["うどん・そば",...
    "健康",...
    "牛丼",...
    "定食",...
    "ラーメン",...
    "寿司",...
    "丸亀",...
    "カレー",...
    "昭和食堂",...
    "コンビニ",...
    "イオン",...
    "ばんや",...
    "うなぎ",...
    "ステーキ",...
    "大将軍",...
    "天ぷら",...
    "揚げ物",...
    "新規開拓",...
    "からよし",...
    "手作り",...
    "全家福",...
    "ファボ",...
    "焼き肉",...
    "食べ放題",...
    "イタリアン",...
    "Mc'donald",...
    "中華",...
    "餃子",...
    "ファミレス"];
lunch = [
    "学食",...
    "将軍バーガー",...
    "モス",...
    "アルビス",...
    "シャトレーゼ",...
    "パン",...
    "グランブッフェ",...
    "コストコ"];
dinner = [
    "贅",...
    "しゃぶしゃぶ",...
    "扇屋",...
    "伝五郎",...
    "魂心家"];
gro = [
    "GB's cafe",...
    "金沢",...
    "BurgerKing",...
    "さわやか",...
    "信州そば",...
    "飛騨牛",...
    "叙々苑"];
switch period
    case 'l'
        mise = [common lunch];
        len = length(mise);
    case 'd'
        mise = [common dinner];
        len = length(mise);
end

r = randi(10); 
if r == 1
    mise = [mise gro];
end

reverseStr = '';
n = 40;
l = length(mise);
% time = 0.0001;
for i = 1:n
    ind = randi(l, 1);
    msg = sprintf(mise(ind));
    str = strcat(reverseStr, msg);
    fprintf(str);
    reverseStr = repmat(sprintf('\b'), 1, length(char(msg)));
    time = 0.009545 * exp(0.04652 * i);
    pause(time)
end

%ループ後
fprintf('\n')
for i = 1:10
    disp(msg)
end
if ind > len
    figure(...
        'MenuBar', 'none',...
        'Position', [680 678 650 250],...
        'Color', 'k');
    str = sprintf("GO TO HELL\n☆★☆ %s ★☆★", msg);
    text(0.5, 0.5, str,...
        'Color', 'r',...
        'FontSize', 35,...
        'FontName', 'FixedWidth',...
        'HorizontalAlignment', 'center');
    axis off
end
end